name: Build & Release CTAG TBD Arduino Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up directories
        run: |
          mkdir -p build/esp32 build/rp2040

      - name: Copy esp32 core and libraries
        run: |
          cp -r hardware/esp32/* build/esp32/
          mkdir -p build/esp32/libraries
          cp -r libraries/* build/esp32/libraries/

      - name: Copy rp2040 core and libraries
        run: |
          cp -r hardware/rp2040/* build/rp2040/
          mkdir -p build/rp2040/libraries
          cp -r libraries/* build/rp2040/libraries/

      - name: Structure and zip cores for Arduino
        run: |
          cd build
          mv esp32 esp32_tmp
          mkdir -p esp32/1.0.0
          mv esp32_tmp/* esp32/1.0.0/
          mv rp2040 rp2040_tmp
          mkdir -p rp2040/1.0.0
          mv rp2040_tmp/* rp2040/1.0.0/
          cd esp32
          zip -r ../esp32-1.0.0.zip .
          cd ..
          cd rp2040
          zip -r ../rp2040-1.0.0.zip .
          cd ..

      - name: Calculate file sizes and prepare JSON
        run: |
          # Dateigrößen berechnen
          echo "ESP32_SIZE=$(stat -c%s build/esp32-1.0.0.zip)" >> $GITHUB_ENV
          echo "RP2040_SIZE=$(stat -c%s build/rp2040-1.0.0.zip)" >> $GITHUB_ENV

          # SHA256 berechnen
          RP2040_SHA=$(sha256sum build/rp2040-1.0.0.zip | awk '{ print $1 }')
          ESP32_SHA=$(sha256sum build/esp32-1.0.0.zip | awk '{ print $1 }')

          # JSON-Datei erzeugen
          cp docs/package_template.json docs/package_dadamachines_ctag_tbd_index.json
          sed -i "s|__RP2040_SHA__|SHA-256:${RP2040_SHA}|" docs/package_dadamachines_ctag_tbd_index.json
          sed -i "s|__ESP32_SHA__|SHA-256:${ESP32_SHA}|" docs/package_dadamachines_ctag_tbd_index.json
          sed -i "s|__RP2040_SIZE__|${RP2040_SIZE}|" docs/package_dadamachines_ctag_tbd_index.json
          sed -i "s|__ESP32_SIZE__|${ESP32_SIZE}|" docs/package_dadamachines_ctag_tbd_index.json

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            build/esp32-1.0.0.zip
            build/rp2040-1.0.0.zip
            docs/package_dadamachines_ctag_tbd_index.json
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
